# Default settings for your application
BIG_MODEL = "chat_gpt"
PORT = 3002
SMALL_MODEL = "pythia"
HOST = "127.0.0.1"
OPENAI_API_KEY = "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"
DATA_GEN_FILE = "data_gen_type.pkl"